### ISSUE TITLE
labels for issues

### ISSUE THREAD

**Issue by SushiTee** [erdbeere/tml#5]
yea that would be nice... be sure to choose good colors xD

**Comment by erdbeere** [comment]
Done, just tell me if you are missing some labels ;)

**Comment by SushiTee** [comment]
btw... only u can label the issues... so dont forget if someone opens an issue ;)

**Comment by erdbeere** [comment]
Whup, didn't knew that, thanks for the hint :)

**Comment by GreYFoX** [comment]
You can add Sushi to the collab list so he can add labels too, i am sure he won't do something evil :D

**Comment by SushiTee** [comment]
already done ;)

**Comment by GreYFoX** [comment]
:)
