### ISSUE TITLE
Errors that weren't there before

### ISSUE THREAD

**Issue by GreYFoX** [erdbeere/tml#8]
> from teemap import Teemap <br/>
> t = Teemap('maps/ctf1.map')<br/>
> 
> Traceback (most recent call last):<br/>
>  File "<pyshell#1>", line 1, in <module><br/>
>    t = Teemap('maps/ctf1.map')<br/>
> TypeError: **init**() takes exactly 1 argument (2 given)<br/>

**Comment by SushiTee** [comment]
the error message should tell u the solution...
u have to use it like this:

<code>
from teemap import Teemap
t = Teemap()
t.load("maps/ctf1.map")
t.save("maps/test.map")
</code>

anyway... invalid

**Comment by GreYFoX** [comment]
> init() takes exactly 1 argument (2 given)

i gave 1 argument not 2 
this is what made me confused 

i don't mean to spam sorry

**Comment by SushiTee** [comment]
you did give the function 2 arguments as its defined like this:

<pre><code>
def __init__(self):
    # ....
</code></pre>


the self parameter is the Teemap itself and is automatically passed ;)

**Comment by GreYFoX** [comment]
hey i am no python expert, i am an end user here :D

i can only learn how to edit this, if i can make sense of the output and the input i guess that will be soon when the output is somewhat more organised at the rate you guys work this is soon

i love what you did you both are great

**Comment by erdbeere** [comment]
Hey,
sorry, the documentation is a bit outdated, I should update it :D The errormessage itself is created by python, not by us ;) Also note this lib should be included in other programs (e.g. online map editor) and is not intended to be for an end user - of course you can do this, but it wont' be _that_ comfortable (especially without any python skills) :D
Anyway thanks for the bug report, it's nice to see that people are interested in this project!

**Comment by GreYFoX** [comment]
it's just an expression, if i just get some free time i will trace it's code until i can know what to expect. but this won't be soon.

and of course i am interested, a lightweight tool like this can do wonders
